CC 85 Unify the way SVG icons are used
chasha-church/venus pull request #14
Opened 2024-03-28 13:17 UTC by ArtsemiLasyi

2024-03-29 07:30 UTC, 17Sergey requested changes

2024-03-29 07:30 UTC, 17Sergey commented on src/components/common/Icons/DonateIcon.tsx
Everything is great, just a little fix to make these components the best:
Let me show you this file with some fixes:
```
type ContactsIconProps = {
  width?: number,
  height?: number,
  color?: string
} & ComponentProps<'svg'>; // Now our Icon accepts all props from svg that we might need

export const ContactsIcon: React.FC<ContactsIconProps> = (
    { width = 36, height = 36, color = "", children, ...props }
) => {
    return (
        <SvgLoader {...props} width={width} height={height} path={"Contacts"}>
            {children} /* Below is explanation why */
        </SvgLoader>
    );
}
```

2024-03-29 07:30 UTC, 17Sergey commented on src/components/common/Icons/DonateIcon.tsx
Now we are able to call our icon like that:
```<ContactsIcon />
<ContactsIcon stroke="#000" />
```
Or even like that:
```
<ContactsIcon width={36} fill="#000">
     <SvgProxy selector="rect" fill={"#FFF"} />
</ContactsIcon>
```

2024-03-29 07:30 UTC, 17Sergey commented on src/components/common/Icons/DonateIcon.tsx
Could you please refactor it like this or if you think it's a bad idea please let me know we'll discuss later.

2024-03-29 07:30 UTC, 17Sergey commented on src/components/common/Icons/DonateIcon.tsx
And please add empty lines to some files)))

2024-03-29 07:49 UTC, ArtsemiLasyi commented on src/components/common/Icons/DonateIcon.tsx
@17Sergey, the idea was to encapsulate all logic of showing this icon. We just call `<SomeIcon someProp={someValue}/>` and that is it. So, at level of big components we don't know about using SvgLoader or some another libs. It allow us to change the realization of showing icon in one place. We can change the lib or get rid of it and for big components nothing changes.
Btw, I think that children for icon is unnecessary prop.
If we will need some additional customization of our icons, we will change only icon and add some new props for SomeIcon with default values

2024-03-29 07:51 UTC, ArtsemiLasyi commented on src/components/common/Icons/DonateIcon.tsx
> And please add empty lines to some files)))

It will be fixed by #15. We will go through all our project and change code style for it

2024-04-16 12:20 UTC, PavelPyasecky approved these changes

2024-04-16 17:03 UTC, 17Sergey approved these changes

2024-04-16 17:27 UTC, merged