CC-36 Add News block to HomePage
chasha-church/venus pull request #3
Opened 2023-12-29 16:30 UTC by PavelPyasecky

[CC-36](https://pavelpiasetski.atlassian.net/browse/CC-36)

2024-01-17 20:38 UTC, 17Sergey reviewed
I'm so sorry that I created a Content component and you need to change so many paths....

2024-01-17 20:38 UTC, 17Sergey commented on src/components/Home/Home.tsx
> +    object-fit: cover;
start

2024-01-17 20:38 UTC, 17Sergey commented on src/components/Home/Home.tsx
> +    object-fit: cover;
111

2024-01-17 20:45 UTC, 17Sergey commented on src/components/Content/Home/NewsBlock/NewsCard/NewsCard.tsx
> +    image: any
I think it's better to set 
`image: string `
because it's usually a path like '../src/assets/img1.jpg' that we send as `src` in `img` tag

2024-01-17 20:49 UTC, 17Sergey commented on src/components/Content/Home/PreviewBlock/PreviewBlock.tsx
> +
Maybe we should delete this empty line

2024-01-17 20:51 UTC, 17Sergey requested changes
Heey I'd like to fix those 2 minor notes and create a pull request. I don't know if it's a good idea.

2024-01-17 20:51 UTC, 17Sergey commented on src/components/Content/Home/PreviewBlock/PreviewBlock.tsx
> +
Maybe we should delete this empty line

2024-01-17 21:34 UTC, closed without merging

2024-01-18 16:35 UTC, PavelPyasecky commented
Follow https://github.com/chasha-church/venus/pull/5