CC-40 Investigate SVG image implementation
chasha-church/venus pull request #8
Opened 2024-02-01 16:06 UTC by PavelPyasecky

[CC-40](https://pavelpiasetski.atlassian.net/browse/CC-40)

2024-02-01 20:48 UTC, 17Sergey commented
Great job! I like the idea of creating SvgContainer for no-repeating svg code. Commented one file that's better to fix

2024-02-01 20:51 UTC, 17Sergey requested changes

2024-02-01 20:51 UTC, 17Sergey commented on src/components/common/SvgContainer/SvgContainer.tsx
> +                <SvgProxy selector="ellipse" fill={color} />
In our svg there is no `ellipse` tag. So we don't need it.
![image](https://github.com/chasha-church/venus/assets/77524020/3ce6e6c9-6826-42e5-b21f-ae1bdf498c05)

2024-02-02 09:32 UTC, PavelPyasecky commented
@17Sergey After rereading your comment I've understood that making SvgContainer component as common was not really good idea. I've moved it to the NewsBlock.

2024-02-02 16:52 UTC, 17Sergey approved these changes

2024-02-02 16:52 UTC, 17Sergey commented
Great job! Everything is ready

2024-02-02 16:53 UTC, merged